### ISSUE TITLE
Bug since latest VSCode update

### ISSUE THREAD

**Issue by CYB3RL1F3** [pgsandstrom/package-json-upgrade#12]
Hello,
I noticed a bug since latest VSCode update. "dependency not found" is displayed with all dependencies, it can't find versions and forthcoming ones as well.
Could you have a look?

Thanks a lot!

**Comment by CYB3RL1F3** [comment]
Sorry for the wrong issue, it was finally due to a bad configuration following this update.

**Comment by olemarius** [comment]
> Sorry for the wrong issue, it was finally due to a bad configuration following this update.

what did you do to fix this? I have the same issue.
