### ISSUE TITLE
Support private registry

### ISSUE THREAD

**Issue by meriturva** [pgsandstrom/package-json-upgrade#2]
We have here private npm registry with .npmrc file as:

`@myscope:registry=https://..../repository/....`

but extension just not recognizes private packages, is it possible to support that case?

Thanks so mutch!

**Comment by pgsandstrom** [comment]
This should be possible. I'll have to investigate how complex it will be, but right now is seems doable. Thanks for the suggestion!

**Comment by pgsandstrom** [comment]
I just published v1.0.5 that should resolve this issue. The extension should now read the npm configuration correctly and apply it to all npm calls. If you run into problems I have added a configuration that disables this feature. Please let me know how it works out!

**Comment by meriturva** [comment]
I'm sorry but I get always the same message.
Do I have to check error messages on which output window?

**Comment by pgsandstrom** [comment]
What is the message you get? "Dependency not found"?

I dont think you currently can get very good debug log from the extension. I'll investigate, maybe that would be a good thing to add to the next release.

**Comment by meriturva** [comment]
yes i have just : Dependency not found

**Comment by pgsandstrom** [comment]
I have released version 1.0.6 that fixes an issue with scoped registry. Hopefully this will solve your problem!

**Comment by meriturva** [comment]
No way....just see image attached:
![image](https://user-images.githubusercontent.com/5664195/75189338-41217a00-574e-11ea-8b5e-124896af32ab.png)

`npm outdated` works great at least!

**Comment by pgsandstrom** [comment]
Aha! Thanks for the screenshot! Currently this extension only shows major, minor and patch-upgrades, not pre-releases. But it would make sense to show pre-releases if the currently used version is a pre-release. I'll fix this to the next version.

And maybe I should add an option to always show pre-releases. I'll think about it.

**Comment by pgsandstrom** [comment]
I have released v1.1.0 with a fix. Hopefully we got it this time :)

**Comment by meriturva** [comment]
Unfortunately not but I have started to debug directly your extension (unfortunately i have really short time to spend on it).

Any way on extension debug I have:

`failed to load dependency @aulos/font. Error: {"headers":{"date":["Mon, 09 Mar 2020 21:10:55 GMT"],"content-type":["application/json"],"content-length":["21"],"connection":["keep-alive"],"set-cookie":["__cfduid=d582626528e804d28c725c46d2d8777981583788255; expires=Wed, 08-Apr-20 21:10:55 GMT; path=/; domain=.npmjs.org; HttpOnly; SameSite=Lax"],"expect-ct":["max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\""],"vary":["Accept-Encoding"],"server":["cloudflare"],"cf-ray":["5717c9151a46cd1e-FCO"],"x-fetch-attempts":["1"]},"statusCode":404,"code":"E404","method":"GET","uri":"https://registry.npmjs.org/@aulos/font","body":{"error":"Not found"},"pkgid":"@aulos/font","message":"404 Not Found - GET https://registry.npmjs.org/@aulos/font - Not found"}`

Secondly, I just navigated on your code and I see how you use npm-registry-fetch and your issue (we hope they will answer your requests). Anyway seems that options on call:
`const json = (await npmRegistryFetch.json(dependencyName, conf)) as NpmData`
are not correct.

![image](https://user-images.githubusercontent.com/5664195/76259057-1b6b9900-6255-11ea-9e5c-7e3c63ebd013.png)

I guess i had to find something relate to https://github.com/npm/npm-registry-fetch#-optsscoperegistry . am i correct?

**Comment by pgsandstrom** [comment]
Too bad! It's really no problem, this thread has improved my extension sooo much, even though we haven't fixed your issue.

You're right, it does relate to that. I send in the entire config object to npm-registry-fetch, and it should successfully parse all registrys, scopes, and scoped registrys. In your case it tries to find "@aulos/font" in the default registry, which I guess is incorrect.

Could you share your entire npm config? If you can't share it publicly, you could also mail it to me att hello@persandstrom.com. It would be very interesting to see what it is in the config that is parsed incorrectly.

**Comment by meriturva** [comment]
And this thread just start me to study how to develop vscode extension so I'm really glad to help you!
I will send you an email tomorrow or in few days....there is nothing urgent here so we have time to catch where problem is!

Thanks.

**Comment by meriturva** [comment]
Email sent right now! So thanks.

**Comment by pgsandstrom** [comment]
I tried to replicate the error with your config, but I failed. Everything worked for me. I just made a commit that logs a whole lot more when an error occurs. If you have the time, run the latest commit in developer mode and mail me the output. It should contain the dependency that caused the error, the entire config used, and all error information.

**Comment by meriturva** [comment]
Log sent!
Really thanks for your patience!

**Comment by pgsandstrom** [comment]
You were completely right in that the extension failed to check for a local .npmrc! Another improvement :) I have added a commit that should fix the issue. If you find the time, please test it out. Otherwise I will make a release in a few days.

**Comment by meriturva** [comment]
Great great great ....

![image](https://user-images.githubusercontent.com/5664195/77438162-c5b2f700-6de5-11ea-8bf7-862e46b1f305.png)

it works!
So thanks I have learned a lot about vs extension and npm api....so thanks again!

**Comment by pgsandstrom** [comment]
Awesome! My pleasure, it seems we both learned a lot :)
