### ISSUE TITLE
Publish package to Open VSX Registry

### ISSUE THREAD

**Issue by jablonski** [pgsandstrom/package-json-upgrade#22]
Hi,

is it possible that you publish "package-json-upgrade" to https://open-vsx.org/?

This would allow to use this highly useful package with VSCode compatible forks (e.g. VSCodium) or use it in Gitpod (https://gitpod.io/).

Thank you very much,
Maik

**Comment by pgsandstrom** [comment]
Thank you for the suggestion! Happy to hear that you are enjoying the extension :) 

I have now published the extension on open-vsx:

https://open-vsx.org/extension/codeandstuff/package-json-upgrade

I have started the process of becoming a verified publisher, so the displayed warning should disappear eventually.
