### ISSUE TITLE
Update All doesn't follow Ignore Versions

### ISSUE THREAD

**Issue by acgritt** [pgsandstrom/package-json-upgrade#23]
When using the Update All Packages option, it doesn't follow the settings for the Ignore Versions. I had manually updated items in the Ignore Patterns so I cannot confirm if there is an issue there as well. However, I would expect that if I say ignore rxjs >= 7 or @types/node >= 13 and then do an update all it wouldn't install rxjs 7.30 and @types/node 16.

**Comment by pgsandstrom** [comment]
Thank you for the bug report! I've confirmed the bug. I'll release a fix in a few days.

**Comment by pgsandstrom** [comment]
1.5.3 has been released and should fix the issue. Let me know if you run into any bugs!
