### ISSUE TITLE
[Feature Request] peerDependencies support

### ISSUE THREAD

**Issue by ondrovic** [pgsandstrom/package-json-upgrade#24]
Seems as though it isn't working for `peerDependencies`

OS Info:
WindowsBuildLabEx            : 19041.1.amd64fre.vb_release.191206-1406
WindowsCurrentVersion     : 6.3
WindowsEditionId               : Professional
WindowsProductName       : Windows 10 Pro 

VS Code Info:
Version: 1.59.1

Package Json Upgrade Version: 1.5.3

After looking through the code, it isn't a bug, looks like `peerDependencies` aren't configured in `npm.ts`

![package-json](https://user-images.githubusercontent.com/3682042/131853849-07a61b7e-a830-4240-b3e9-654e7c62ffcc.png)
![peerDeps](https://user-images.githubusercontent.com/3682042/131855190-3c512cf6-28b3-4a6a-afde-d9922897201a.png)
![devDeps](https://user-images.githubusercontent.com/3682042/131855244-7eecc033-0d0f-4806-a6b2-c0e4c81e05ea.png)
![apollo-client](https://user-images.githubusercontent.com/3682042/131855290-ff1aacb8-916f-4792-af6e-b98d25a13244.png)

**Comment by ondrovic** [comment]
Think I have it worked out [Peer Support PR](https://github.com/pgsandstrom/package-json-upgrade/pull/25)

**Comment by pgsandstrom** [comment]
Thank you for the feedback! However, there are two issues with supporting peerDependencies.

First of all, a peerDependency can be expressed in a more complicated semver range than other dependencies, for example like `>= 1.5.2 < 2`. Currently the extension cannot handle this in a nice way, it would just remove the upper limit.

Secondly, peerDependency should not be updated as aggressively as other dependencies. PeerDependencies are supposed to be [as lenient as possible](https://nodejs.org/es/blog/npm/peer-dependencies/#using-peer-dependencies). So I wouldn't want to encourage updating them whenever possible. I guess there would be some value in knowing when a peerDependency has a new major release, but that feels like it is outside the scope of this extension.

**Comment by ondrovic** [comment]
Thanks for the explanation as to why peerDependency support isn't included. I guess with any update to any package should be considered and tested.
