### ISSUE TITLE
The extension doesn't look into the peerDependencies

### ISSUE THREAD

**Issue by PhiLhoSoft** [pgsandstrom/package-json-upgrade#27]
When I update the package "xxx" in the (dev)dependencies, I generally want to update also the peerDependencies.
But your useful package doesn't seem to look into them. Is this possible to add this?

**Comment by pgsandstrom** [comment]
Thank you for the feedback! Usually you want peerDependencies to be [as leniant as possible](https://nodejs.org/es/blog/npm/peer-dependencies/#using-peer-dependencies). To avoid encouraging bad practices, I have choosen to not support it with this extension.

**Comment by mmospanenko** [comment]
Will be good to be informed that peerDeps are outdated, not necessary to update it automatically. This is critically for Angular monorepo libs, etc.

**Comment by pgsandstrom** [comment]
While I think it would be confusing for the average user, I could see that some users would like this feature. I would agree to add it behind a setting. Currently Im quite busy, but I'll accept a PR.
