### ISSUE TITLE
command 'package-json-upgrade.toggle-show' not found

### ISSUE THREAD

**Issue by Pfurr** [pgsandstrom/package-json-upgrade#36]
hi, i have this error what i go to menu vsc osx -> command + p -> "Toggle showing package.json available updates": --> return popup which this error --> command 'package-json-upgrade.toggle-show' not found Ps. I reinstalled plugin and it return some issue.

**Comment by pgsandstrom** [comment]
Im unable to replicate this issue. Quite a lot has happened since this was posted. Can someone confirm that it is still present, and give me some more debug information? I'll close in the meantime.
