### ISSUE TITLE
Display every update possible ?

### ISSUE THREAD

**Issue by raskyer** [pgsandstrom/package-json-upgrade#37]
Hello,

I would like to know if it's possible to add a feature that will display every possible update.
Major, minor and bugfix instead of only showing the final last version ?

It would be helpful for project that has various dependencies that are stuck to some major but can keep updating minor or bugfix. 

Thanks

**Comment by pgsandstrom** [comment]
In the context menu you can see major/minor/patch/pre-release versions listed if they are available.

If you dont want to display certain versions there is a config called `ignoreVersions`. There you can add `{\"@types/node\": \">=12\"}` to ignore versions ranges. The version ranges should be as specifide by node-semver: https://github.com/npm/node-semver?tab=readme-ov-file#ranges

Does this sufficiently cover your usecase? I'll try to improve the documentation in the readme.
