### ISSUE TITLE
Latest tag ignored

### ISSUE THREAD

**Issue by meriturva** [pgsandstrom/package-json-upgrade#4]
Hi @pgsandstrom 
I have noted that we have a few "false positive" updated packages that are not the latest.

See for example image:
![image](https://user-images.githubusercontent.com/5664195/82496072-6a9f3700-9aec-11ea-8a75-de39227a4724.png)

I guess your extension has to mark `karma-teamcity-reporter` as not update to latest package.
Instead, `npm outdate` cmd works well.

is it possible to base warning on the real latest tagged version? I have another few examples to show you about that (es: https://www.npmjs.com/package/@progress/kendo-drawing)

**Comment by pgsandstrom** [comment]
Hi again! :)

It seems reasonable to only act on versions that are equal to or lesser than the "latest"-tag. I'll check it out.

**Comment by meriturva** [comment]
Thanks! I have noted that there are few libraries published with wrong numbers and then corrected by the publisher (but old and wrong version still present) so we have to check just the latest.

**Comment by pgsandstrom** [comment]
I have released version 1.2.0. Did it resolve the issue correctly?

**Comment by meriturva** [comment]
It seems to be fixed!
So thanks...again!
