### ISSUE TITLE
Don't show suggestions in merge editor

### ISSUE THREAD

**Issue by neorth** [pgsandstrom/package-json-upgrade#41]
Right now the plugin is visible in the merge editor. A suggestion is to hide it in that place.
<img width="1201" alt="image" src="https://user-images.githubusercontent.com/8577089/202120106-fbd5a94e-8d83-4922-8aa2-6847f7c49e63.png">

**Comment by pgsandstrom** [comment]
Thats a good idea. I'll get around to it eventually, but I have a lot on my plate currently. In the meantime I would very much welcome PRs.

**Comment by pgsandstrom** [comment]
Just released v2.1.3 that fixes this. Please let me know if you run into any issues with it! :)
