### ISSUE TITLE
Quick Fix icon doesn’t appear when language mode associated to `package.json` is not `json` (e.g. `jsonc`, etc.)

### ISSUE THREAD

**Issue by ymeine** [pgsandstrom/package-json-upgrade#48]
Hi,

Lately I noticed I had issues displaying the quick fix icon to automate the version update for me.

I first thought it was a regression in the extension itself, though the rest worked perfectly fine.

But after a bit of investigation, I figured out it was due to my vscode setup, and more specifically my settings. That’s where I realized I had added a global file association: `*.json` ⇒ `jsonc`. For the record and IIRC I think I did it for `deno.json` files.

While this file association is debatable - I even removed it and I’m fine with it - I think that having a feature break because of that is not resilient. If for any reason some user wants to associate JSON files to another language mode then it will break.

I’m not familiar with the Quick Fix API in vscode and its constraints, so I did a quick search: 

- API is [defined here](https://code.visualstudio.com/api/references/vscode-api#languages.registerCodeActionsProvider) and accepts a documents filter as its first parameter
- you use it there: [package-json-upgrade/src/extension.ts#L86](https://github.com/pgsandstrom/package-json-upgrade/blob/4f0c0b407e635f102cd9a11dbcc2e54c1a1830a3/src/extension.ts#L86) and you specify only the language `json`

I guess: 

- either there’s a way to filter it by file name (`package.json`) instead of by syntax and [it looks like it’s feasible](https://code.visualstudio.com/api/references/vscode-api#DocumentFilter)
- or you add `jsonc` specifically since it seems to be at the moment the only real common alternative language mode for JSON, you even [activate the extension on jsonc files](https://github.com/pgsandstrom/package-json-upgrade/blob/4f0c0b407e635f102cd9a11dbcc2e54c1a1830a3/package.json#L29) yourself

----

Btw, not related: would a link to the extension on the vscode marketplace be relevant in the readme file of the repo? Or in the about section of the repo itself?

**Comment by ymeine** [comment]
After testing on a cloned version of your repo, I confirm that replacing: 

```typescript
vscode.languages.registerCodeActionsProvider('json', new UpdateAction(), {
  providedCodeActionKinds: UpdateAction.providedCodeActionKinds,
}),
```

with: 

```typescript
vscode.languages.registerCodeActionsProvider({pattern: '**/package.json'}, new UpdateAction(), {
  providedCodeActionKinds: UpdateAction.providedCodeActionKinds,
}),
```
works.

Would it be a welcome change?

**Comment by pgsandstrom** [comment]
Thanks for the very clear problem description and solution :) Awesome!

It seems to work like you describe. I have release v2.1.1 with your fix. Let me know if you run into any problems.

**Comment by ymeine** [comment]
I just tried it, and it works with any language set for the document. Thanks for publishing it so fast! (even before pushing to master on this repo? I couldn't even see the commit related to the fix 😄 )

And thanks for your extension too btw :)

**Comment by pgsandstrom** [comment]
Hah, I forgot to push the changes! Thanks for reminding me :D
