### ISSUE TITLE
Cursor IDE Support

### ISSUE THREAD

**Issue by melloware** [pgsandstrom/package-json-upgrade#51]
Love your plugin but I just recently switched to Cursor IDE which is a VSCode IDE with AI: https://cursor.sh/

Your plugin works for the most part but the light bulb never appears for me to update the extension.

![image](https://github.com/pgsandstrom/package-json-upgrade/assets/4399574/c164b819-1826-40d5-9936-8a42720331f6)

**Comment by pgsandstrom** [comment]
I would guess this is a bug with the Cursor IDE. This is outside of the scope of this project and I wont investigate it. However, if someone would create a PR with some kind of workaround that would make it work in Cursor IDE, I will be open to that.

**Comment by melloware** [comment]
Let me see if I can report it to Cursor.

**Comment by melloware** [comment]
i will close for now as this is not your issue.
