### ISSUE TITLE
showing the older version of react@rc as update available

### ISSUE THREAD

**Issue by tachsin** [pgsandstrom/package-json-upgrade#52]
<img width="824" alt="image" src="https://github.com/user-attachments/assets/4f469a10-47c7-494e-a881-2c4b2af94f45">

**Comment by pgsandstrom** [comment]
This is an issue with React, they dont conform to semver 2.0. I have created an issue, lets see what happens:

https://github.com/facebook/react/issues/30415

**Comment by tachsin** [comment]
`yarn add react@rc react-dom@rc` automatically gets the latest version, it's just annoying to see update available, if it cannot be fixed, is there at least a way to exclude the packages from checking?

**Comment by pgsandstrom** [comment]
Yes, you can add regexp matches for packages that you dont want to check by adding this to your settings.json:

`  "package-json-upgrade.ignorePatterns": ["^react$"],`
